### ISSUE TITLE
Add basic tests?

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/scrapers#18]
We have tests for some of the datasets, but not others. EIP Infrastructure and FERC 714 seem to be missing. At the same time, we still have a test for the deprecated EPA IPM data.

Do we feel like these mocked unit tests provide value? Should they be updated to cover all current datasets?

**Comment by zschira** [comment]
Closing see the new [archiver](https://github.com/catalyst-cooperative/pudl-archiver) repo
