### ISSUE TITLE
Add retry capabilities to scraping to verify that downloaded archives are valid

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/scrapers#51]
Some data sources (like EPA CEMS) are prone to creating bad archives due to flaky downloads. Currently the only solution to this is to manually verify archives and rerun the scraping process as needed. To enable the automation of our scraping/archiving, we need to add automated retry capabilities that will verify the archives and rerun the scraping process if it fails.

**Comment by zaneselvans** [comment]
There's also #39 which is related to this.

**Comment by zschira** [comment]
Ah ok. I'm going to close this one and add that one to the epic.
