### ISSUE TITLE
Create github action for running the scraping/archiving process at desired frequencies

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/scrapers#53]
Once the archiver/scraper repos have been combined, and we have high level scripts for managing the process, it should be very easy to create github actions for automating the archiving process. New data is released at various frequencies for the different data sources incorporated in PUDL, so we can create multiple actions that run at frequencies reflective of this.

**Comment by zaneselvans** [comment]
I am so excited for this to finally happen!
